config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'index#index'

  get 'index/update_notes/:ne_lat/:ne_lng/:sw_lat/:sw_lng' => 'index#update_notes',
      defaults: { format: 'json' },
      :constraints => { :ne_lat => /.*/, :ne_lng => /.*/,
                        :sw_lat => /.*/, :sw_lng => /.*/}

  put 'notes/:id/stars/:user_id' => 'notes#add_star'
  delete 'notes/:id/stars/:user_id' => 'notes#delete_star'

  resources :notes
  resources :albums

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  has_many :collections, :dependent => :destroy
  has_many :albums, :through => :collections

  has_many :stars, :dependent => :destroy
  has_many :users, :through => :stars

  before_save :set_point
  before_update :set_point

  validates :title, :body, :user_id, presence: true
  validates :latitude, :longitude, :user_id, numericality: true

  # Finds all public and user's notes close to location to certain degree
  scope :find_by_proximity,
        lambda { |location, current_user, bounds = nil|
          if bounds.nil?
            linestring_text = get_linestring__by_loc(location)
            pub_notes = []
          else
            linestring_text = get_linestring_by_bounds(bounds)
            pub_notes = Note.find_by_sql("
            SELECT id, latitude, longitude, user_id
            FROM notes
            FORCE INDEX (index_notes_on_latlon)
            WHERE
              private=false AND user_id!=#{current_user.id} AND
              MBRContains(GeomFromText( '#{linestring_text}' ), notes.latlon)
            ORDER BY LEFT(created_at, 10) DESC, star_count DESC LIMIT 30")
          end

          # TODO: prevent double user load on index page
          user_notes = Note.find_by_sql("
            SELECT id, latitude, longitude, user_id
            FROM notes
            FORCE INDEX (index_notes_on_latlon)
            WHERE
              user_id=#{current_user.id} AND
              MBRContains(GeomFromText( '#{linestring_text}' ), notes.latlon)")
          # order first by day (not time), then by star count

          user_notes + pub_notes
        }

  # By default, use the GEOS implementation for spatial columns
  self.rgeo_factory_generator = RGeo::Geos.method(:factory)

  # But use a geographic implementation for the :latlon column.
  set_rgeo_factory_for_column(:latlon, RGeo::Geographic.spherical_factory)

  # Uses lat and lng to create and set point within note
  def set_point
    if self.latitude_was != self.latitude || self.longitude_was != self.longitude
      self[:latlon] = RGeo::Geographic.spherical_factory(:srid => 4326)
                          .point(self[:longitude], self[:latitude])
    end
  end

  # Gets text representation of linestring centered around location
  def Note.get_linestring__by_loc(location)
    "LINESTRING(#{location.lng - 1} #{location.lat - 0.5},
                #{location.lng + 1} #{location.lat + 0.5})"
  end

  # Gets text representation of linestring based on map bounds
  def Note.get_linestring_by_bounds(bounds)
    "LINESTRING(#{bounds[:ne][:lng]} #{bounds[:ne][:lat]},
                #{bounds[:sw][:lng]} #{bounds[:sw][:lat]})"
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where(user_id: current_user.id).order('updated_at DESC')
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    respond_to do |format|
      if @note.save
        @form_id = params[:form_id]
        format.js
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/stars
  def add_star
    note_id = params[:id]
    note = Note.find(note_id)
    respond_to do |format|
      if note.stars.create!(note_id: note_id, user_id: params[:user_id])
        note.star_count = note.star_count + 1
        note.save
        format.json { render json: params, status: :ok }
      else
        format.json { render json: params, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/stars
  def delete_star
    note = Note.find(params[:id])
    respond_to do |format|
      if note.stars.where(user_id: params[:user_id]).destroy_all
        note.star_count = note.star_count - 1
        note.save
        format.json { render json: params, status: :ok }
      else
        format.json { render json: params, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        @form_id = params[:form_id]
        format.js
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      @form_id = params[:form_id]
      format.js
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
      if @note.user_id != current_user.id && @note.private
        raise 'Invalid permissions'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body, :latitude, :longitude, :private,
                                   :user_id, { :album_ids => [] }, :form_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
  def cache_key_for_notes
    count          = current_user.notes.count
    max_updated_at = current_user.notes.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "notes/all-#{count}-#{max_updated_at}"
  end
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 10 %>
  </div>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>

  <h4>Albums to include in...</h4>
  <% current_user.albums.each do |album| %>
    <div>
      <%= check_box_tag 'album' + album.id.to_s, album.id, @note.albums.include?(album), :name => 'note[album_ids][]' -%>
      <%= label_tag 'album' + album.id.to_s, album.title %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit 'Submit', :class => 'button' %>
  </div>
<% end %>

<% if @note.new_record? %>
  <%= javascript_include_tag 'geolocation' %>
<% end %>

app/views/notes/_noteForm.html.erb
<div id="overlay" class="">
  <form id="noteView" action="/notes/" method="post" data-remote="true" accept-charset="UTF-8">
    <div>
      <input type="text" name="note[title]" placeholder="Title" value="">
      <br>
      <textarea name="note[body]" rows="10" placeholder="Write anything you want about this location!"></textarea>
    </div>
    <div id="album-div">
      <button id="album-button" class="secondary tiny dropdown button" data-dropdown="album-dropdown"
              aria-controls="album-dropdown" aria-expanded="false" type="button" href="#">+ Album</button>
      <ul id="album-dropdown" class="f-dropdown" data-dropdown-content="" aria-hidden="true"></ul>
    </div>
    <input type="hidden" name="note[latitude]" value="" readonly="readonly">
    <input type="hidden" name="note[longitude]" value="" readonly="readonly">
    <input type="hidden" name="authenticity_token" value="" readonly="readonly">
    <input type="hidden" name="note[album_ids][]" value="" readonly="readonly">
    <div id="radio-group" class="">
      <input id="privateTrue" type="radio" name="note[private]" value="" readonly="readonly">
      <label for="privateTrue">Private</label>
      <input id="privateFalse" type="radio" checked="" name="note[private]" value="" readonly="readonly">
      <label for="privateFalse">Public</label>
    </div>
    <div>
      <button id="submit-edit-button" class="button tiny right" type="submit">Edit</button>
      <button id="delete-button" class="alert tiny right hide" type="submit">Delete</button>
      <button id="cancel-button" class="secondary tiny right hide" type="button">Cancel</button>
    </div>
    <input type="hidden" name="_method" value="patch" readonly="readonly">
  </form>
</div>

app/views/notes/create.js.erb
$(function() {
  alert('Note saved successfully!');
  app.noteCreated(<%= raw @note.to_json(:include => :albums) %>);
});

app/views/notes/destroy.js.erb
$(function() {
  alert('Note deleted successfully!');
  app.noteDeleted();
});

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<script>
  $(document).ready(function() {
    var table = $('#notes-table');
    table.DataTable();
    table.removeClass('hide');
});
</script>


  <h1>Listing Notes</h1>
  <% unless @notes.empty? %>
    <table id="notes-table" class="hide">
      <thead>
      <tr>
      <% 5.times do %>
        <th></th>
      <% end %>
      </tr>
      </thead>

      <tbody>
      <% cache do %>
      <% @notes.each do |note| %>
          <tr>
            <td><%= note.title %></td>
            <td><%= link_to 'Show', note %></td>
            <td><%= link_to 'Edit', edit_note_path(note) %></td>
            <td><a href="#" class="reveal-link"
                   data-note='<%= raw note.to_json(:only => [ :title, :id ]) %>'
                >Show/Edit</a></td>
            <td><%= link_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  <% else %>
    Nothing yet!
    <br>
  <% end %>


<br>

<%= link_to 'Create Note', new_note_path, class:'button' %>

<div id="editModal" class="reveal-modal xlarge" data-reveal aria-hidden="true"
     data-session='<%= session[:_csrf_token] %>'
     data-albums='<%= raw current_user.albums.to_json(:only => [:title, :id]) %>'>
  <div id="form" class="medium-6 columns">
    <%= render 'notes/noteForm' %>
  </div>

  <div class="medium-6 columns full">
    <div id="map-canvas"></div>
  </div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBTrBJkp-8i6MZKKotUoTnzoUiXV_zlIVg' %>
<%= javascript_include_tag 'geolocation' %>
<%= javascript_include_tag 'noteview' %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @note.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @note.longitude %>
</p>

<p>
  <strong>Albums:</strong>
  <% @note.albums.each do |album| %>
    <%= link_to album.title, album %><%= ', ' unless album == @note.albums.last %>
  <% end %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/notes/update.js.erb
$(function() {
  alert('Note updated!');
  app.noteUpdated(<%= raw @note.to_json(:include => :albums) %>);
});