config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'index#index'

  get 'index/update_notes/:ne_lat/:ne_lng/:sw_lat/:sw_lng' => 'index#update_notes',
      defaults: { format: 'json' },
      :constraints => { :ne_lat => /.*/, :ne_lng => /.*/,
                        :sw_lat => /.*/, :sw_lng => /.*/}

  put 'notes/:id/stars/:user_id' => 'notes#add_star'
  delete 'notes/:id/stars/:user_id' => 'notes#delete_star'

  resources :notes
  resources :albums

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :notes, :through => :collections
  has_many :collections, :dependent => :destroy

  validates :title, :description, presence: true
  validates :user_id, numericality: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = current_user.albums
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.create(album_params)
    @album.user_id = current_user.id

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :description, :user_id, { :note_ids => [] })
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <h4>Notes to include...</h4>
  <% current_user.notes.each do |note| %>
    <div>
      <%= check_box_tag 'note' + note.id.to_s, note.id, @album.notes.include?(note), :name => 'album[note_ids][]' -%>
      <%= label_tag 'note' + note.id.to_s, note.title -%>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Submit', :class => 'button' %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<script>
  $(document).ready(function() {
    $('#album-table').DataTable();
} );
</script>

<h1>Listing Albums</h1>

<% unless @albums.empty? %>
<table id="album-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <% 3.times do %>
      <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.description %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  Nothing yet!
  <br>
<% end %>

<br>

<%= link_to 'New Album', new_album_path, :class => 'button' %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<p>
  <strong>Notes:</strong>
  <% @album.notes.each do |note| %>
    <%= link_to note.title, note %><%= ', ' unless note == @album.notes.last %>
  <% end %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>